### PR TITLE
feat: Add new feature with 42 files

### PR DESCRIPTION
**Pull request by SakibvHossain**

### CODE REVIEW

**Review by SakibvHossain — COMMENTED** [review]
Please check. I hope everything is okey

**Review by anika-as — COMMENTED** [review]
Everything seems fine. Can you please check homepages.css again I think there is some problem

**Review by SakibvHossain — COMMENTED** [review]
I have double checked the mentioned file. Yeah, everything is good.

**Review by anika-as — COMMENTED** [review]
Well done after all.

**Review by anika-as — APPROVED** [review]

**Pull request merged**
